package edu.xxx.algorithms.uguide;

import lombok.Getter;

/**
 * @author XXX
 */
@Getter
public class TChange {

  /**
   * TupleOID, generated by BART, starting from 1
   */
  private final int oid;

  /**
   * Line index, generated by hydra, starting from 0
   */
  private final int lineIndex;

  /**
   * Attribute, or column name
   */
  private final String attribute;

  /**
   * Wrong value, injected by BART
   */
  private final String wrongValue;

  /**
   * Correct value
   */
  private final String correctValue;

  public TChange(int oid, int lineIndex, String attribute, String wrongValue, String correctValue) {
    this.oid = oid;
    this.lineIndex = lineIndex;
    this.attribute = attribute;
    this.wrongValue = wrongValue;
    this.correctValue = correctValue;
  }
}
