package edu.fudan.algorithms.uguide;

import java.util.Objects;
import lombok.Getter;

/**
 * @author Lingfeng
 */
@Getter
public class TCell {

  /**
   * Line index, generated by hydra, starting from 0
   */
  private final int lineIndex;

  /**
   * Attribute, or column name
   */
  private final String attribute;

  /**
   * Value
   */
  private final String value;

  public TCell(int lineIndex, String attribute, String value) {
    this.lineIndex = lineIndex;
    this.attribute = attribute;
    this.value = value;
  }

  @Override
  public String toString() {
    return this.lineIndex + "_" + this.attribute + "_" + this.value;
  }

  @Override
  public int hashCode() {
    return Objects.hash(this.lineIndex, this.attribute, this.value);
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj) {
      return true;
    }
    if (obj == null) {
      return false;
    }
    if (getClass() != obj.getClass()) {
      return false;
    }
    TCell other = (TCell) obj;
    if (this.lineIndex != other.lineIndex ||
        !Objects.equals(this.attribute, other.attribute) ||
        !Objects.equals(this.value, other.value)
    ) {
      return false;
    }
    return true;
  }
}
